---
- name: Configure locale
  locale_gen:
    name: "{{ raspberry_pi_locale }}"
    state: present

- name: Configure timezone
  timezone:
    name: "{{ raspberry_pi_timezone }}"

- name: Configure keyboard
  template:
    src: ./templates/keyboard.j2
    dest: /etc/default/keyboard
