---
- import_tasks: localization.yml

- import_tasks: hostname.yml
  tags: notest

- import_tasks: network.yml
  when: raspberry_pi_configure_network | bool

- import_tasks: wifi.yml
  when: raspberry_pi_use_wifi | bool

- import_tasks: upgrade_and_packages.yml

- import_tasks: configure.yml
