---
- name: Upgrade System
  apt:
    upgrade: dist
    update_cache: true
  when: raspberry_pi_upgrade_system | bool

- name: Install packages
  apt:
    name: "{{ raspberry_pi_packages }}"
    update_cache: true
