---
dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: raspberry-pi
    image: geerlingguy/docker-debian11-ansible
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible
  inventory:
    host_vars:
      raspberry-pi:
        raspberry_pi_locale: es_AR.UTF-8
        raspberry_pi_timezone: America/Argentina/Buenos_Aires
        raspberry_pi_keyboard_layout: es
        raspberry_pi_hostname: my-home-pie
        raspberry_pi_configure_network: true
        raspberry_pi_ip_address: 192.168.0.2/24
        raspberry_pi_routers: 192.168.0.1
        raspberry_pi_dns_servers: [1.1.1.1, 1.0.0.1]
        raspberry_pi_use_wifi: true
        raspberry_pi_wifi_country: AR
        raspberry_pi_wifi_ssid: myHomeWiFiNetwork
        raspberry_pi_wifi_password: someWifiPassword
        raspberry_pi_packages:
          - git
          - vim
verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
