---
name: test

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * 6'
  workflow_dispatch:

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install YAMLlint
        run: pip3 install ansible ansible-lint docker jmespath molecule[docker] yamllint

      - name: Run Molecule test
        run: molecule test

